#  This is a new React Native project, bootstrapped using @react-native-community/cli.

#Android

#  Step 1: Start Metro
# Using npm
#npm start

# OR using Yarn
#yarn start

#Step 2: Build and run your app

# Using npm
#npm run android

# OR using Yarn
#yarn android


#iOS